Sorted: 'Congratulations! You have been sorted into {house}'
NoPermission: 'You do not have permission to execute this command'
Choices:
  1:
    name: "Gryffindor"
    command: "pex user {player} group add {house}"
  2:
    name: "Hufflepuff"
    command: "pex user {player} group add {house}"
  3:
    name: "Slytherin"
    command: "pex user {player} group add {house}"
  4:
    name: "Ravenclaw"
    command: "pex user {player} group add {house}"