name: TheSortingHat
version: ${project.version}
main: me.rafaelfaustini.thesortinghat.TheSortingHat
authors: [RafaelFaustini]
description: Based on Harry Potter's sorting hat
website: www.rafaelfaustini.com.br

commands:
  sort:
    description: Sorts from elements and executes commands from config
    aliases: [sortear,escolher,choose,s]
  sortinghat:
    description: TheSortingHat master command
    aliases: [sh]
